name: ar_ruler_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vector_math: ^2.2.0
  ar_flutter_plugin:
    path: ar_flutter_plugin_autodetect
  #ar_flutter_plugin: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  # force modern, v2-embedding-safe versions
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  geolocator: ^14.0.2
  geolocator_android: ^5.0.2
